jobs:
  semgrep:
    requires:
      - ~pr
      - ~commit
    environment:
      YAHOO_SEMGREP_ENFORCING: true
    template: python-2204/validate_semgrep
  pulsar-helm:
    requires: [~pr, ~commit]
    image: docker.ouroath.com:4443/gap-tools:latest

    steps:
      - install: |
          echo ${HELM_VERSION}
          cd /tmp
          curl https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz | tar xvfz -
          mv linux-amd64/helm /usr/local/bin
          chmod 755 /usr/local/bin/helm
          pip3 install yq
          cd $SD_SOURCE_DIR
          export CHARTS_PATH=${SD_SOURCE_DIR}/charts/pulsar
      - lint: |
          helm --debug lint ${CHARTS_PATH}
      - package: |
          CHART_VERSION=$(curl -s "https://edge.artifactory.ouroath.com:4443/artifactory/api/storage/cms_java/pulsar-helm?lastModified" | jq -r '.uri' | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+(-[0-9]*)).*/\1/p')          
          if [[ "$CHART_VERSION" = "" ]];
          then
            echo "artifact not available"
            helm --debug package ${CHARTS_PATH} --destination $SD_ARTIFACTS_DIR
          else 
            echo "artifact available"
            ARTIFACT_VER=$(echo $CHART_VERSION | cut -d "-" -f1)
            MINOR_VER=$(echo $CHART_VERSION | cut -d "-" -f2)
            echo "minor version before increment: ${MINOR_VER}"
            MINOR_VER=$((MINOR_VER+1))
            echo "minor version after increment: ${MINOR_VER}"
            CHART_VERSION=${ARTIFACT_VER}-${MINOR_VER}
            echo "Chart Version: ${CHART_VERSION}"
            helm --debug package ${CHARTS_PATH} --destination $SD_ARTIFACTS_DIR --version $CHART_VERSION
          fi
      - artifactory-publish: |
          export CHART_NAME=pulsar
          if [ -z ${SD_PULL_REQUEST} ]
          then
            if [[ "$CHART_VERSION" = "" ]];
            then
              CHART_VERSION=$(helm show chart ${CHARTS_PATH}| yq -r .version)
            fi
            echo "Chart Version: ${CHART_VERSION}" 
            export SRC_FILE=$SD_ARTIFACTS_DIR/${CHART_NAME}-${CHART_VERSION}.tgz
            export DEST_FULLPATH="/cms_java/pulsar-helm/${CHART_NAME}-${CHART_VERSION}.tgz"
            echo "SRC_FILE: ${SRC_FILE}"
            scp -P 4443 "$SRC_FILE" "artifactory-ssh-proxy.corp.yahoo.com:/${DEST_FULLPATH}"
          fi
