#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

## start
components:
  # zookeeper
  zookeeper: true
  # bookkeeper
  bookkeeper: true
  # bookkeeper - autorecovery
  autorecovery: true
  # broker
  broker: true
  # functions
  functions: true
  # proxy
  proxy: false
  # toolset
  toolset: false
  # pulsar manager
  pulsar_manager: false

## Images
##
## Control what images to use for each component
images:
  broker:
    repository: docker.ouroath.com:4443/cms
    tag: 2.7.48.12-yahoo
    pullPolicy: IfNotPresent
  bookie:
    repository: docker.ouroath.com:4443/cms
    tag: 2.7.48.12-yahoo
    pullPolicy: IfNotPresent

monitoring:
  # monitoring - prometheus
  prometheus: true
  # monitoring - grafana
  grafana: true
  # monitoring - node_exporter
  node_exporter: false
  # alerting - alert-manager
  alert_manager: false

zookeeper:
  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    data:
      name: data
      size: 5Gi
      local_storage: false
      ## If you already have an existent storage class and want to reuse it, you can specify its name with the option below
      ##
      storageClassName: gp2-small
      #
      ## Instead if you want to create a new storage class define it below
      ## If left undefined no storage class will be defined along with PVC
      ##
      # storageClass:
        # type: pd-ssd
        # fsType: xfs
        # provisioner: kubernetes.io/gce-pd
  configData:
    # we use `bin/pulsar` for starting bookie daemons
    PULSAR_LOG_APPENDER: "RollingFile"
    PULSAR_ROUTING_APPENDER_DEFAULT: "RollingFile"
bookkeeper:
  replicaCount: 3
  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    journal:
      name: journal
      size: 16Gi
      local_storage: false
      ## If you already have an existent storage class and want to reuse it, you can specify its name with the option below
      ##
      storageClassName: io2-small
    ledgers:
      name: ledgers
      size: 16Gi
      local_storage: false
      ## If you already have an existent storage class and want to reuse it, you can specify its name with the option below
      ##
      storageClassName: gp2-small
  tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "application"
          effect: "NoSchedule"
  configData:
    # we use `bin/pulsar` for starting bookie daemons
    PULSAR_LOG_APPENDER: "RollingFile"
    PULSAR_ROUTING_APPENDER_DEFAULT: "RollingFile"
    PULSAR_LOG_CONF: "/pulsar/conf/log4j2.yaml"
    tlsTrustStoreType: "PEM"
    tlsClientAuthentication: "true"
    tlsCertificatePath: "/pulsar/conf/broker-cert.pem"
    tlsKeyStore: "/pulsar/conf/broker-key.pem"
    authorizedRoles: "admin,client,localhost"
    bookieAuthProviderFactoryClass: "org.apache.pulsar.BookieAuthTLSFactory"
    tlsProviderFactoryClass: "org.apache.bookkeeper.tls.TLSContextFactory"
    tlsCertFilesRefreshDurationSeconds: "900"
    tlsAllowedRoles: "client,admin"
    tlsEnabledCipherSuites: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    tlsEnabledProtocols: "TLSv1.2"
    tlsKeyStoreType: "PEM"
    tlsTrustStore: "/pulsar/conf/cacert.pem"
    PULSAR_MEM: >
      -Xms128m
      -Xmx256m
      -XX:MaxDirectMemorySize=256m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=33
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
      -XX:+PrintGCDetails
      -verbosegc
      -XX:+PerfDisableSharedMem
      -XX:+PrintGCDetails
      -XX:+IgnoreUnrecognizedVMOptions
      -Xloggc:/pulsar/bookie-gc.log
      -XX:G1LogLevel=finest

broker:
  replicaCount: 3
  serviceAccount:
    name: athenz-cert-issuer
    annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::454759051864:role/irsa-awstest
  configData:
   functionsWorkerEnabled: "false"
   PULSAR_LOG_APPENDER: "RollingFile"
   PULSAR_ROUTING_APPENDER_DEFAULT: "RollingFile"
   PULSAR_LOG_CONF: "/pulsar/conf/log4j2.yaml"
   authenticationEnabled: "true"
   authenticationProviders: "org.apache.pulsar.broker.authentication.AuthenticationProviderTls"
   authorizationEnabled: "true"
   superUserRoles: "localhost,client,admin"
   tlsCertificateFilePath: "/pulsar/conf/broker-cert.pem"
   tlsKeyFilePath: "/pulsar/conf/broker-key.pem"
   tlsRequireTrustedClientCertOnConnect: "false"
   tlsCertRefreshCheckDurationSec: "300"
   tlsTrustCertsFilePath: "/pulsar/conf/cacert.pem"
   brokerServicePortTls: "6651"
   tlsAllowInsecureConnection: "true"
   tlsEnabled: "true"
   tlsCiphers: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
   tlsProtocols: "TLSv1.2"
   webServicePortTls: "4443"
   brokerClientAuthenticationParameters: "tlsCertFile:/pulsar/conf/client-cert.pem,tlsKeyFile:/pulsar/conf/client-key.pem"
   brokerClientAuthenticationPlugin: "org.apache.pulsar.client.impl.auth.AuthenticationTls"
   brokerClientTrustCertsFilePath: "/pulsar/conf/cacert.pem"
   brokerClientTlsEnabled: "true"
   bookkeeperTLSCertificateFilePath: "/pulsar/conf/client-cert.pem"
   bookkeeperTLSClientAuthentication: "true"
   bookkeeperTLSKeyFilePath: "/pulsar/conf/client-key.pem"
   bookkeeperTLSKeyFileType: "PEM"
   bookkeeperTLSProviderFactoryClass: "org.apache.bookkeeper.tls.TLSContextFactory"
   bookkeeperTLSTrustCertTypes: "PEM"
   bookkeeperTLSTrustCertsFilePath: "/pulsar/conf/cacert.pem"
   bookkeeperTlsCertFilesRefreshDurationSeconds: "300"
   brokerClientAuthenticationParameters: "tlsCertFile:/pulsar/conf/client-cert.pem,tlsKeyFile:/pulsar/conf/client-key.pem"
   brokerClientAuthenticationPlugin: "org.apache.pulsar.client.impl.auth.AuthenticationTls"
   # client cert
   tlsTrustCertsFilePath: "/pulsar/conf/cacert.pem"
   authPlugin: "org.apache.pulsar.client.impl.auth.AuthenticationTls"
   authParams: "tlsCertFile:/pulsar/conf/client-cert.pem,tlsKeyFile:/pulsar/conf/client-key.pem"
   brokerServiceUrl: "pulsar+ssl://localhost:6651"
   webServiceUrl: "https://localhost:4443"


  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    data:
      name: data
      size: 5Gi
      local_storage: false
      ## If you already have an existent storage class and want to reuse it, you can specify its name with the option below
      ##
      storageClassName: gp2-small
      #
      ## Instead if you want to create a new storage class define it below
      ## If left undefined no storage class will be defined along with PVC
      ##
      # storageClass:
        # type: pd-ssd
        # fsType: xfs
        # provisioner: kubernetes.io/gce-pd
