{{- if .Values.components.logs }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.logs.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
{{ toYaml .Values.logs.customLabels | indent 4 }}
    component: {{ .Values.logs.component }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.logs.component }}
  updateStrategy:
{{ toYaml .Values.logs.updateStrategy | indent 4 }}
  template:
    metadata:
      labels:
        {{- include "pulsar.standardLabels" . | nindent 8 }}
{{ toYaml .Values.logs.customLabels | indent 8 }}
        component: {{ .Values.logs.component }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
    {{- if .Values.logs.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.logs.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.logs.tolerations }}
      tolerations:
{{ toYaml .Values.logs.tolerations | indent 8 }}
    {{- end }}
      serviceAccountName: "{{ .Values.logs.service_account.name }}"
      dnsPolicy: {{ .Values.logs.dnsPolicy }}
      hostNetwork: {{ .Values.logs.hostNetwork }}
      initContainers:
      ## sia init container
      - name: init-sia
        image: "{{ .Values.images.sia.repository }}/{{ .Values.images.sia.tag }}"
        imagePullPolicy: {{ .Values.images.sia.pullPolicy }}
        command: ['sh', '-c', "while :; do /usr/sbin/siad -regionalsts -cmd post && break; done"]
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        resources:
{{ toYaml .Values.athenz.sia.resources | indent 10 }}
        volumeMounts:
{{ toYaml .Values.athenz.sia.init_volumeMounts | indent 10 }}
      ## cameo init container
      - name: init-cameo
        image: "{{ .Values.images.cameo.repository }}/{{ .Values.images.cameo.tag }}"
        imagePullPolicy: {{ .Values.images.cameo.pullPolicy }}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        env:
{{ toYaml .Values.athenz.cameo.env | indent 10 }}
          - name: ATHENZ_SERVICE_CERT_PATH
            value: {{ .Values.athenz.certs.path }}/{{ .Values.athenz.domain }}.{{ .Values.logs.service_account.name }}.cert.pem
          - name: ATHENZ_SERVICE_KEY_PATH
            value: {{ .Values.athenz.certs.key }}/{{ .Values.athenz.domain }}.{{ .Values.logs.service_account.name }}.key.pem
          - name: INIT_RUN
            value: "true"
        resources:
{{ toYaml .Values.athenz.cameo.resources | indent 10 }}
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 10 }}
      containers:
      - name: sia
        image: "{{ .Values.images.sia.repository }}/{{ .Values.images.sia.tag }}"
        imagePullPolicy: {{ .Values.images.sia.pullPolicy }}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        resources:
{{ toYaml .Values.athenz.sia.resources | indent 10 }}
        volumeMounts:
{{ toYaml .Values.athenz.sia.volumeMounts | indent 10 }}
      - name: cameo
        image: "{{ .Values.images.cameo.repository }}/{{ .Values.images.cameo.tag }}"
        imagePullPolicy: {{ .Values.images.cameo.pullPolicy }}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        resources:
{{ toYaml .Values.athenz.cameo.resources | indent 10 }}
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 10 }}
        env:
{{ toYaml .Values.athenz.cameo.env | indent 10 }}
          - name: ATHENZ_SERVICE_CERT_PATH
            value: {{ .Values.athenz.certs.path }}/{{ .Values.athenz.domain }}.{{ .Values.logs.service_account.name }}.cert.pem
          - name: ATHENZ_SERVICE_KEY_PATH
            value: {{ .Values.athenz.certs.key }}/{{ .Values.athenz.domain }}.{{ .Values.logs.service_account.name }}.key.pem
      - name: "{{ template "pulsar.fullname" . }}-{{ .Values.logs.component }}"
        image: "{{ .Values.images.logs.repository }}/{{ .Values.images.logs.tag }}"
        imagePullPolicy: {{ .Values.images.logs.pullPolicy }}
        securityContext:
{{ toYaml .Values.logs.container.securityContext | indent 10 }}
        env:
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
      {{- if .Values.logs.resources }}
        resources:
{{ toYaml .Values.logs.resources | indent 10 }}
      {{- end }}
      {{- if .Values.logs.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.logs.volumeMounts | indent 10 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
{{ toYaml .Values.athenz.volumes | indent 6 }}
      - name: sia
        configMap:
          name: "{{ .Values.logs.service_account.configmap }}"
{{ toYaml .Values.athenz.sia.config_map | indent 10 }}
{{ toYaml .Values.logs.volumes | indent 6 }}
{{- end }}