{{- if .Values.components.logs }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.logs.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
{{ toYaml .Values.logs.customLabels | indent 4 }}
    component: {{ .Values.logs.component }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.logs.component }}
  updateStrategy:
{{ toYaml .Values.logs.updateStrategy | indent 4 }}
  template:
    metadata:
      labels:
        {{- include "pulsar.standardLabels" . | nindent 8 }}
{{ toYaml .Values.logs.customLabels | indent 8 }}
        component: {{ .Values.logs.component }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
    {{- if .Values.logs.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.logs.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.logs.tolerations }}
      tolerations:
{{ toYaml .Values.logs.tolerations | indent 8 }}
    {{- end }}
      serviceAccountName: "{{ .Values.logs.service_account.name }}"
      dnsPolicy: {{ .Values.logs.dnsPolicy }}
      hostNetwork: {{ .Values.logs.hostNetwork }}
      initContainers:
      ## sia init container
      {{- include "pulsar.init-sia" . | nindent 6 }}
      {{$data := dict "service_account" .Values.logs.service_account.name }}
      {{- include "pulsar.init-cameo" (merge (dict "Args" $data) . ) | nindent 6 }}
      containers:
      {{- include "pulsar.sia" . | nindent 6 }}
      {{$data := dict "service_account" .Values.logs.service_account.name }}
      {{- include "pulsar.cameo" (merge (dict "Args" $data) . ) | nindent 6 }}
      - name: "{{ template "pulsar.fullname" . }}-{{ .Values.logs.component }}"
        image: "{{ .Values.images.logs.repository }}/{{ .Values.images.logs.tag }}"
        imagePullPolicy: {{ .Values.images.logs.pullPolicy }}
        securityContext:
{{ toYaml .Values.logs.container.securityContext | indent 10 }}
        env:
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
      {{- if .Values.logs.resources }}
        resources:
{{ toYaml .Values.logs.resources | indent 10 }}
      {{- end }}
      {{- if .Values.logs.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.logs.volumeMounts | indent 10 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      {{$data := dict "service_account_configmap" .Values.logs.service_account.configmap }}
      {{- include "pulsar.sia-volumes" (merge (dict "Args" $data) . ) | nindent 6 }}
{{ toYaml .Values.logs.volumes | indent 6 }}
{{- end }}