# add athenz changes

  {{- if or .Values.components.pulsar_manager .Values.extra.pulsar_manager }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.pulsar_manager.service_account.configmap }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.pulsar_manager.component }}
data:
  sia_config: |
    {
      "version": "1.0.0",
      "service": "{{ .Values.pulsar_manager.service_account.name }}",
      "accounts": [
        {
          "domain":  "{{ .Values.auth.authentication.athenz.certs.domain }}",
          "account": "{{ .Values.auth.authentication.athenz.certs.aws_account_id }}"
        }
      ]
    }
  {{- end }}
