#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if or .Release.IsInstall .Release.IsUpgrade .Values.initialize }}
{{- if .Values.components.broker }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_metadata.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.pulsar_metadata.component }}
spec:
# This feature was previously behind a feature gate for several Kubernetes versions and will default to true in 1.23 and beyond
# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
{{- if .Values.job.ttl.enabled }}
  ttlSecondsAfterFinished: {{ .Values.job.ttl.secondsAfterFinished }}
{{- end }}
  template:
    spec:
      securityContext:
{{ toYaml .Values.pod.securityContext | indent 8 }}
      serviceAccountName: "{{ .Values.bookkeeper.service_account.name }}"
    {{- if .Values.broker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.broker.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.broker.tolerations }}
      tolerations:
{{- with .Values.broker.tolerations }}
{{ toYaml . | indent 8 }}
{{- end }}
    {{- end }}
      initContainers:
      ## sia init container
      {{- include "pulsar.init-sia" . | nindent 6 }}
      {{$data := dict "service_account" .Values.bookkeeper.service_account.name }}
      {{- include "pulsar.init-cameo" (merge (dict "Args" $data) . ) | nindent 6 }}
      ## zk keystore generation init container
      - name: init-zkcertgen
        image: "{{ .Values.images.broker.repository }}:{{ .Values.images.broker.tag }}"
        imagePullPolicy: {{ .Values.images.broker.pullPolicy }}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        env:
          - name: ATHENZ_SERVICE_CERT_PATH
            value: {{ .Values.athenz.certs.path }}/{{ .Values.athenz.domain }}.{{ .Values.bookkeeper.service_account.name }}.cert.pem
          - name: ATHENZ_SERVICE_KEY_PATH
            value: {{ .Values.athenz.certs.key }}/{{ .Values.athenz.domain }}.{{ .Values.bookkeeper.service_account.name }}.key.pem
        command: ["sh", "-c"]
        args:
          - >
            echo "jks cert script started";
            bin/jks-cert-generator.sh {{ .Values.athenz.domain }}.{{ .Values.bookkeeper.service_account.name }}.key.pem {{ .Values.athenz.domain }}.{{ .Values.bookkeeper.service_account.name }}.cert.pem;
            echo "zookeeper configurations";
            cat conf/zookeeper.conf;
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 10 }}
      {{- if .Values.pulsar_metadata.configurationStore }}
      - name: wait-cs-ready
        image: "{{ .Values.pulsar_metadata.image.repository }}:{{ .Values.pulsar_metadata.image.tag }}"
        imagePullPolicy: {{ .Values.pulsar_metadata.image.pullPolicy }}
        command: ["sh", "-c"]
        args:
          - >-
            until nslookup {{ .Values.pulsar_metadata.configurationStore}}; do
              sleep 3;
            done;
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
      {{- end }}
      - name: wait-zookeeper-ready
        image: "{{ .Values.pulsar_metadata.image.repository }}:{{ .Values.pulsar_metadata.image.tag }}"
        imagePullPolicy: {{ .Values.pulsar_metadata.image.pullPolicy }}
        command: ["sh", "-c"]
        args:
          - >-
            export OPTS="$OPTS {{ .Values.bookkeeper.configData.zkClientJvmArgs }}";
            {{- if $zk:=.Values.pulsar_metadata.userProvidedZookeepers }}
            until bin/pulsar zookeeper-shell -server {{ $zk }} ls {{ or .Values.metadataPrefix "/" }}; do
              echo "user provided zookeepers {{ $zk }} are unreachable... check in 3 seconds ..." && sleep 3;
            done;
            {{ else }}
            until nslookup {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ add (.Values.zookeeper.replicaCount | int) -1 }}.{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}.{{ template "pulsar.namespace" . }}; do
              sleep 3;
            done;
            {{- end}}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 10 }}
      # This initContainer will wait for bookkeeper initnewcluster to complete
      # before initializing pulsar metadata
      - name: pulsar-bookkeeper-verify-clusterid
        image: "{{ .Values.pulsar_metadata.image.repository }}:{{ .Values.pulsar_metadata.image.tag }}"
        imagePullPolicy: {{ .Values.pulsar_metadata.image.pullPolicy }}
        command: ["sh", "-c"]
        args:
        - >
          export OPTS="$OPTS {{ .Values.bookkeeper.configData.zkClientJvmArgs }}";
          bin/apply-config-from-env.py conf/bookkeeper.conf;
          {{- include "pulsar.toolset.zookeeper.tls.settings" . | nindent 10 }}
          until bin/bookkeeper shell whatisinstanceid; do
            sleep 3;
          done;
        envFrom:
        - configMapRef:
            name: "{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}"
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 10 }}
      containers:
      - name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_metadata.component }}"
        image: "{{ .Values.pulsar_metadata.image.repository }}:{{ .Values.pulsar_metadata.image.tag }}"
        imagePullPolicy: {{ .Values.pulsar_metadata.image.pullPolicy }}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
      {{- if .Values.pulsar_metadata.resources }}
        resources:
{{ toYaml .Values.pulsar_metadata.resources | indent 10 }}
      {{- end }}
        command: ["sh", "-c"]
        args:
          - |
            export OPTS="$OPTS {{ .Values.bookkeeper.configData.zkClientJvmArgs }}";
            {{- include "pulsar.toolset.zookeeper.tls.settings" . | nindent 12 }}
            bin/pulsar initialize-cluster-metadata \
              --cluster {{ template "pulsar.cluster.name" . }} \
              --zookeeper {{ template "pulsar.zookeeper.connect" . }}{{ .Values.metadataPrefix }} \
              {{- if .Values.pulsar_metadata.configurationStore }}
              --configuration-store {{ template "pulsar.configurationStore.connect" . }}{{ .Values.pulsar_metadata.configurationStoreMetadataPrefix }} \
              {{- end }}
              {{- if not .Values.pulsar_metadata.configurationStore }}
              --configuration-store {{ template "pulsar.zookeeper.connect" . }}{{ .Values.metadataPrefix }} \
              {{- end }}
              {{- if .Values.pulsar_metadata.proxyUrl }}
              --proxy-url {{ .Values.pulsar_metadata.proxyUrl }} \
              {{- end }}
              {{- if .Values.pulsar_metadata.proxyProtocol }}
              --proxy-protocol {{ .Values.pulsar_metadata.proxyProtocol }} \
              {{- end }}
              {{- if .Values.pulsar_metadata.webUrl }}
              --web-service-url {{ .Values.pulsar_metadata.webUrl }} \
              {{- else }}
              --web-service-url http://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.http }}/ \
              {{- end }}
              {{- if .Values.pulsar_metadata.webUrlTls }}
              --web-service-url-tls {{ .Values.pulsar_metadata.webUrlTls }} \
              {{- else }}
              --web-service-url-tls https://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.https }}/ \
              {{- end }}
              {{- if .Values.pulsar_metadata.brokerUrl }}
              --broker-service-url {{ .Values.pulsar_metadata.brokerUrl }} \
              {{- else }}
              --broker-service-url pulsar://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.pulsar }}/ \
              {{- end }}
              {{- if .Values.pulsar_metadata.brokerUrlTls }}
              --broker-service-url-tls {{ .Values.pulsar_metadata.brokerUrlTls }} \
              {{- else }}
              --broker-service-url-tls pulsar+ssl://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.broker.ports.pulsarssl }}/ ;
              {{- end }}
            {{- if .Values.extraInitCommand }}
              {{ .Values.extraInitCommand }}
            {{- end }}
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 10 }}
      volumes:
      {{$data := dict "service_account_configmap" .Values.bookkeeper.service_account.configmap }}
      {{- include "pulsar.sia-volumes" (merge (dict "Args" $data) . ) | nindent 6 }}
      restartPolicy: OnFailure
{{- end }}
{{- end }}
