kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-test-account-binding
  namespace: {{ template "pulsar.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: aws-load-balancer-controller
    namespace: kube-addons
roleRef:
  kind: Role
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
