# serviceaccount and serviceaccount_configmap

{{ if .Values.components.toolset }}
{{$data := dict
  "service_account" .Values.toolset.service_account.name
  "component" .Values.toolset.component
  "annotations" .Values.toolset.service_account.annotations
}}
{{- include "pulsar.service-account" (merge (dict "Args" $data) . ) }}
---
{{$data := dict
  "service_account" .Values.toolset.service_account.name
  "service_account_configmap" .Values.toolset.service_account.configmap
  "component" .Values.toolset.component
}}
{{- include "pulsar.gcp.service-account-configmap" (merge (dict "Args" $data) . ) }}
{{ end }}

