{{- if .Values.components.toolset }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.toolset.component }}-clusterrolebinding"
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.toolset.component }}-clusterrole"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.toolset.service_account.name }}"
    namespace: {{ template "pulsar.namespace" . }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.toolset.component }}-clusterrole"
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - nodes
    verbs:
      - list
      - watch
      - get
---

{{- end }}