#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# add athenz n cameo changes
# deploy zookeeper only when `components.zookeeper` is true
{{- if .Values.components.zookeeper }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.zookeeper.component }}
spec:
  serviceName: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}"
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      {{- include "pulsar.matchLabels" . | nindent 6 }}
      component: {{ .Values.zookeeper.component }}
  updateStrategy:
{{ toYaml .Values.zookeeper.updateStrategy | indent 4 }}
  podManagementPolicy: {{ .Values.zookeeper.podManagementPolicy }}
  template:
    metadata:
      labels:
        {{- include "pulsar.template.labels" . | nindent 8 }}
        component: {{ .Values.zookeeper.component }}
      annotations:
        prometheus.io/scrape: "true"
        {{- if .Values.prometheus.https_scraper }}
        prometheus.io/scheme: "https"
        {{- end }}
        prometheus.io/port: "
        {{- if .Values.prometheus.https_scraper }}
          {{- .Values.zookeeper.ports.https }}
        {{- else }}
          {{- .Values.zookeeper.ports.http }}
        {{- end }}"
        {{- if .Values.zookeeper.restartPodsOnConfigMapChange }}
        checksum/config: {{ include (print $.Template.BasePath "/zookeeper-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.zookeeper.alwaysRestart }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
{{- with .Values.zookeeper.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      securityContext:
{{ toYaml .Values.pod.securityContext | indent 8 }}
    {{- if .Values.zookeeper.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.zookeeper.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.zookeeper.tolerations }}
      tolerations:
{{ toYaml .Values.zookeeper.tolerations | indent 8 }}
    {{- end }}
      topologySpreadConstraints:
        {{- if and .Values.affinity.zone_spread .Values.zookeeper.affinity.zone_spread}}
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchExpressions:
            - key: "app"
              operator: In
              values:
              - "{{ template "pulsar.name" . }}"
            - key: "release"
              operator: In
              values:
              - {{ .Release.Name }}
            - key: "component"
              operator: In
              values:
              - {{ .Values.zookeeper.component }}
        {{- end }}
      affinity:
        {{- if and .Values.affinity.anti_affinity .Values.zookeeper.affinity.anti_affinity}}
        podAntiAffinity:
          {{ if eq .Values.zookeeper.affinity.type "requiredDuringSchedulingIgnoredDuringExecution"}}
          {{ .Values.zookeeper.affinity.type }}:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - "{{ template "pulsar.name" . }}"
              - key: "release"
                operator: In
                values:
                - {{ .Release.Name }}
              - key: "component"
                operator: In
                values:
                - {{ .Values.zookeeper.component }}
            topologyKey: "kubernetes.io/hostname"
        {{ else }}
          {{ .Values.zookeeper.affinity.type }}:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - "{{ template "pulsar.name" . }}"
                    - key: "release"
                      operator: In
                      values:
                      - {{ .Release.Name }}
                    - key: "component"
                      operator: In
                      values:
                      - {{ .Values.zookeeper.component }}
                topologyKey: "kubernetes.io/hostname"
        {{ end }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.zookeeper.gracePeriod }}
      serviceAccountName: "{{ .Values.zookeeper.service_account.name }}"
      initContainers:
      ## sia init container
      {{- include "pulsar.init-sia" . | nindent 6 }}
      {{$data := dict "service_account" .Values.zookeeper.service_account.name }}
      {{- include "pulsar.init-cameo" (merge (dict "Args" $data) . ) | nindent 6 }}
      ## initialize jks cert generation for zookeeper zk client usage
      - name: init-zkcertgen
        image: "{{ .Values.images.zookeeper.repository }}:{{ .Values.images.zookeeper.tag }}"
        imagePullPolicy: {{ .Values.images.zookeeper.pullPolicy }}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        env:
          - name: ATHENZ_SERVICE_CERT_PATH
            value: {{ .Values.athenz.certs.path }}/{{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.cert.pem
          - name: ATHENZ_SERVICE_KEY_PATH
            value: {{ .Values.athenz.certs.key }}/{{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.key.pem
        command: ["sh", "-c"]
        args:
          - >
            echo "jks cert script started";
            bin/jks-cert-generator.sh {{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.key.pem {{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.cert.pem;
            echo "zookeeper configurations";
            cat conf/zookeeper.conf;
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 10 }}
      containers:
      {{- include "pulsar.sia" . | nindent 6 }}
      {{$data := dict "service_account" .Values.zookeeper.service_account.name }}
      {{- include "pulsar.cameo" (merge (dict "Args" $data) . ) | nindent 6 }}
      {{ if .Values.prometheus.https_scraper }}
      - name: stunnel
        image: "{{ .Values.images.stunnel.repository }}:{{ .Values.images.stunnel.tag }}"
        imagePullPolicy: {{ .Values.images.stunnel.pullPolicy }}
        args: ["{{ .Values.zookeeper.ports.https }}", "{{ .Values.zookeeper.ports.http }}", "{{ .Values.athenz.certs.path }}/{{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.cert.pem", "{{ .Values.athenz.certs.key }}/{{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.key.pem", "{{ .Values.athenz.certs.path }}/ca.cert.pem"]
        ports:
        # prometheus needs to access /metrics endpoint
        - name: https
          containerPort: {{ .Values.zookeeper.ports.https }}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        resources:
          requests:
            memory: 50M
            cpu: 10m
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 10 }}
      {{ end }}
      - name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}"
        image: "{{ .Values.images.zookeeper.repository }}:{{ .Values.images.zookeeper.tag }}"
        imagePullPolicy: {{ .Values.images.zookeeper.pullPolicy }}
      {{- if .Values.zookeeper.resources }}
        resources:
{{ toYaml .Values.zookeeper.resources | indent 10 }}
      {{- end }}
        command: ["sh", "-c"]
        args:
        - >
        {{- if .Values.zookeeper.additionalCommand }}
          {{ .Values.zookeeper.additionalCommand }}
        {{- end }}
          bin/apply-config-from-env.py conf/zookeeper.conf;
          {{- include "pulsar.zookeeper.tls.settings" . | nindent 10 }}
          bin/generate-zookeeper-config.sh conf/zookeeper.conf;
          cat conf/zookeeper.conf; crond;
          {{ if .Values.zookeeper.healthCheck.enabled }}
          echo "*/5 * * * *" /pulsar/bin/zookeeper-healthcheck.sh {{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.key.pem  {{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.cert.pem | crontab -;
          {{ end }}
          {{ if .Values.zookeeper.zktls.enabled }}
          echo "setting up jks cert gen script as cron with key " {{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.key.pem;
          (crontab -l; echo "2 1 * * *" /pulsar/bin/jks-cert-generator.sh {{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.key.pem  {{ .Values.athenz.domain }}.{{ .Values.zookeeper.service_account.name }}.cert.pem) | sort -u | crontab -;
          {{ end }}
          OPTS="${OPTS} -Dlog4j2.formatMsgNoLookups=true" exec bin/pulsar zookeeper;
        ports:
        # prometheus needs to access /metrics endpoint
        - name: http
          containerPort: {{ .Values.zookeeper.ports.http }}
        - name: client
          containerPort: {{ .Values.zookeeper.ports.client }}
        - name: follower
          containerPort: {{ .Values.zookeeper.ports.follower }}
        - name: leader-election
          containerPort: {{ .Values.zookeeper.ports.leaderElection }}
        {{- if and .Values.tls.enabled .Values.tls.zookeeper.enabled }}
        - name: client-tls
          containerPort: {{ .Values.zookeeper.ports.clientTls }}
        {{- end }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: ZOOKEEPER_SERVERS
        {{- if .Values.zookeeper.configData.ZOOKEEPER_SERVERS }}
            value: {{ .Values.zookeeper.configData.ZOOKEEPER_SERVERS }}
        {{- else }}
           {{- $global := . }}
            value: {{ range $i, $e := until (.Values.zookeeper.replicaCount | int) }}{{ if ne $i 0 }},{{ end }}{{ template "pulsar.fullname" $global }}-{{ $global.Values.zookeeper.component }}-{{ printf "%d" $i }}{{ end }}
        {{- end }}
          - name: EXTERNAL_PROVIDED_SERVERS
        {{- if .Values.zookeeper.configData.ZOOKEEPER_SERVERS }}
            value: "true"
        {{- else }}
            value: "false"
        {{- end }}
        envFrom:
        - configMapRef:
            name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}"
        {{- $zkConnectCommand := "" -}}
        {{- if .Values.zookeeper.zktls.enabled }}
        {{- $zkConnectCommand = print "openssl s_client -quiet -crlf -connect localhost:" .Values.zookeeper.configData.PULSAR_PREFIX_secureClientPort " -cert /var/lib/sia/certs/" .Values.athenz.domain "." .Values.zookeeper.service_account.name ".cert.pem -key /var/lib/sia/keys/" .Values.athenz.domain "." .Values.zookeeper.service_account.name ".key.pem " -}}
        {{- else -}}
        {{- $zkConnectCommand = print "nc localhost " .Values.zookeeper.ports.client -}}
        {{- end }}
        securityContext:
{{ toYaml .Values.container.securityContext | indent 10 }}
        {{- if .Values.zookeeper.probe.readiness.enabled }}
        readinessProbe:
          exec:
            command:
            - timeout
            - "{{ .Values.zookeeper.probe.readiness.timeoutSeconds }}"
            - bash
            - -c
            - 'echo ruok | {{ $zkConnectCommand }} | grep imok'
          initialDelaySeconds: {{ .Values.zookeeper.probe.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.zookeeper.probe.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.zookeeper.probe.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.zookeeper.probe.readiness.failureThreshold }}
        {{- end }}
        {{- if .Values.zookeeper.probe.liveness.enabled }}
        livenessProbe:
          exec:
            command:
            - timeout
            - "{{ .Values.zookeeper.probe.liveness.timeoutSeconds }}"
            - bash
            - -c
            - 'echo ruok | {{ $zkConnectCommand }} | grep imok'
          initialDelaySeconds: {{ .Values.zookeeper.probe.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.zookeeper.probe.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.zookeeper.probe.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.zookeeper.probe.liveness.failureThreshold }}
        {{- end }}
        {{- if .Values.zookeeper.probe.startup.enabled }}
        startupProbe:
          exec:
            command:
            - timeout
            - "{{ .Values.zookeeper.probe.startup.timeoutSeconds }}"
            - bash
            - -c
            - 'echo ruok | {{ $zkConnectCommand }} | grep imok'
          initialDelaySeconds: {{ .Values.zookeeper.probe.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.zookeeper.probe.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.zookeeper.probe.startup.timeoutSeconds }}
          failureThreshold: {{ .Values.zookeeper.probe.startup.failureThreshold }}
        {{- end }}
        volumeMounts:
{{ toYaml .Values.athenz.volumeMounts | indent 8 }}
        - name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ .Values.zookeeper.volumes.data.name }}"
          mountPath: /pulsar/data
        - name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ .Values.zookeeper.volumes.logs.name }}"
          mountPath: {{ .Values.zookeeper.volumes.logs.mountPath }}
          subPathExpr: $(POD_NAME)
        {{- if and .Values.tls.enabled .Values.tls.zookeeper.enabled }}
        - mountPath: "/pulsar/certs/zookeeper"
          name: zookeeper-certs
          readOnly: true
        - mountPath: "/pulsar/certs/ca"
          name: ca
          readOnly: true
        - name: keytool
          mountPath: "/pulsar/keytool/keytool.sh"
          subPath: keytool.sh
        {{- end }}
        {{ if .Values.zookeeper.healthCheck.enabled }}
        - mountPath: /metrics-data
          name: metrics-volume
        {{ end }}
        {{- if .Values.zookeeper.extraVolumeMounts }}
{{ toYaml .Values.zookeeper.extraVolumeMounts | indent 8 }}
        {{- end }}
      volumes:
      {{$data := dict "service_account_configmap" .Values.zookeeper.service_account.configmap }}
      {{- include "pulsar.sia-volumes" (merge (dict "Args" $data) . ) | nindent 6 }}
      {{- if not (and (and .Values.volumes.persistence .Values.volumes.persistence) .Values.zookeeper.volumes.persistence) }}
      - name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ .Values.zookeeper.volumes.data.name }}"
        emptyDir: {}
      {{- end }}
      {{ if not .Values.zookeeper.volumes.logs2ebs }}
      - name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ .Values.zookeeper.volumes.logs.name }}"
        hostPath:
          path: {{ .Values.zookeeper.volumes.logs.mountPath }}
          type: {{ .Values.zookeeper.volumes.logs.type }}
      {{ end }}
      {{ if .Values.zookeeper.healthCheck.enabled }}
      - name: metrics-volume
        emptyDir: {}
      {{ end }}
      {{- if .Values.zookeeper.extraVolumes }}
{{ toYaml .Values.zookeeper.extraVolumes | indent 6 }}
      {{- end }}
      {{- if and .Values.tls.enabled .Values.tls.zookeeper.enabled }}
      - name: zookeeper-certs
        secret:
          secretName: "{{ .Release.Name }}-{{ .Values.tls.zookeeper.cert_name }}"
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
      - name: ca
        secret:
          secretName: "{{ .Release.Name }}-{{ .Values.tls.ca_suffix }}"
          items:
            - key: ca.crt
              path: ca.crt
      - name: keytool
        configMap:
          name: "{{ template "pulsar.fullname" . }}-keytool-configmap"
          defaultMode: 0755
      {{- end}}
{{- if and (and .Values.persistence .Values.volumes.persistence) .Values.zookeeper.volumes.persistence }}
  volumeClaimTemplates:
  {{ if .Values.zookeeper.volumes.logs2ebs }}
  - metadata:
      name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ .Values.zookeeper.volumes.logs.name }}"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.zookeeper.volumes.logs.size }}
    {{- if .Values.zookeeper.volumes.logs.storageClassName }}
      storageClassName: "{{ .Values.zookeeper.volumes.logs.storageClassName }}"
    {{- else if and (not (and .Values.volumes.local_storage .Values.zookeeper.volumes.logs.local_storage)) .Values.zookeeper.volumes.data.storageClass }}
      storageClassName: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ .Values.zookeeper.volumes.logs.name }}"
    {{- else if and .Values.volumes.local_storage .Values.zookeeper.volumes.logs.local_storage }}
      storageClassName: "local-storage"
    {{- end }}
  {{ end }}
  - metadata:
      name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ .Values.zookeeper.volumes.data.name }}"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.zookeeper.volumes.data.size }}
    {{- if .Values.zookeeper.volumes.data.storageClassName }}
      storageClassName: "{{ .Values.zookeeper.volumes.data.storageClassName }}"
    {{- else if and (not (and .Values.volumes.local_storage .Values.zookeeper.volumes.data.local_storage)) .Values.zookeeper.volumes.data.storageClass }}
      storageClassName: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ .Values.zookeeper.volumes.data.name }}"
    {{- else if and .Values.volumes.local_storage .Values.zookeeper.volumes.data.local_storage }}
      storageClassName: "local-storage"
    {{- end }}
{{- end }}
{{- end }}
