{{- if and (.Values.components.zookeeper) (hasKey .Values.zookeeper.configData "ZOOKEEPER_SERVERS") }}
{{- range $i := untilStep 0 (.Values.zookeeper.replicaCount | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "pulsar.fullname" $ }}-zookeeper-{{ $i }}"
  labels:
    app: "{{ template "pulsar.fullname" $ }}-zookeeper-{{ $i }}"
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    #service.beta.kubernetes.io/load-balancer-source-ranges: {{ $.Values.zookeeper.configData.SUBNETS }}
    #external-dns.alpha.kubernetes.io/hostname: 	{{ template "pulsar.fullname" $ }}-zookeeper-{{ $i }}.{{ $.Values.zookeeper.configData.ROUTE53_HOSTED_ZONE }}
    #prometheus.io/scrape: "true"
    #prometheus.io/scheme: "https"
    #prometheus.io/port: "{{ $.Values.zookeeper.ports.https }}"
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "pulsar.fullname" $ }}-zookeeper-{{ $i }}
  ports:
    - name:  "{{ $.Values.tcpPrefix }}follower"
      port: {{ $.Values.zookeeper.ports.follower }}
      targetPort: {{ $.Values.zookeeper.ports.follower }}
    - name: "{{ $.Values.tcpPrefix }}leader-election"
      port: {{ $.Values.zookeeper.ports.leaderElection }}
      targetPort: {{ $.Values.zookeeper.ports.leaderElection }}
  externalTrafficPolicy: Local
{{- end }}
{{- end }}
